kind: Secret
apiVersion: v1
metadata:
  name: fedora03-ssh-key
data:
  key: >-
    c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCZ1FES0ZJNnN2UWFGNlBpaVZQdkpEUlZMK2dTWm1hUEtWZk1QaHZNeWdtYzltcW1mMWZkc3pGSHVlRitwaGZZK1lDYzFTZXVYbnFGZDNyY2RJdG1wSWNxNDZ5emRSSzlkWmtJL3A2VkhXWG5vOWEvbmVUSWxCVDcxU0kvaHhyRktIeFBhcGxyU2V5ZmpTZU8zK0lXZ24zbDU2R3VhUkcrblhSc3orQVlGUXFMVXFEcHRtZVROdS9QVkppTXV6Wlkva3dWT3JGdnJqL2hyRVZMTVZybks5S0xEaXJ4QVBVYkhXaVhUdXZpUGtLMFE3bGs4T05aRWE3ekFCRE5BM29MQzkyaFRnMnk5cCtoUExmbDJVVjRiblB4NkdsK2lTVnBCSVU5RTZWTjJuUm1YR2Q5UXp5QjB2M0dxeFk4SkhsRk4xV29nWmxvcDNibEZ1Nnl6UTFPcTNrTjBvVmNvRDdoWlA4S3Vxa1kvSTRsQ1NzbFhKM0lYcENvVWxkNmUrWXMzOUNtQm1xYzR3Z0NEcWNVZk9hdDJ0Yk5IajB3eFJ0bjJmanMzZHlNMEVlSVFHMU1KQTR6cmU2eGt1bFFjQXN1K0pmRVVJSW1LeDJIMG9ka2J2S25YajhuS0NxVHdlNk9FZjhmcGVLR3R1TlNsMVFTSkZjV2hGZUFpSjdjUGwrczN6M2M9IGFuc2libGU=
type: Opaque
