apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
  name: fedora03
  finalizers:
    - kubevirt.io/virtualMachineControllerFinalize
  labels:
    app: fedora03
    vm.kubevirt.io/template: fedora-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: "1"
    vm.kubevirt.io/template.version: v0.25.0
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: fedora03
      spec:
        source:
          http:
            url: "http://192.168.123.100:81/Fedora35.qcow2"
        storage:
          resources:
            requests:
              storage: 30Gi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: fedora03
        kubevirt.io/size: small
    spec:
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              configDrive: {}
            source:
              secret:
                secretName: fedora03-ssh-key
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - macAddress: "02:fd:ed:00:00:07"
              masquerade: {}
              model: virtio
              name: default
            - bridge: {}
              macAddress: "02:fd:ed:00:00:08"
              model: virtio
              name: nic-rough-swordtail
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.2.0
        resources:
          requests:
            memory: 4Gi
      evictionStrategy: LiveMigrate
      networks:
        - name: default
          pod: {}
        - multus:
            networkName: gitopsexamples/appnad
          name: nic-rough-swordtail
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: fedora03
          name: rootdisk
        - cloudInitConfigDrive:
            userData: |
              #cloud-config
              user: fedora
              password: virtualizationForFuture
              chpasswd:
                expire: false
          name: cloudinitdisk
