---
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  tektonPipelinesNamespace: pipelines
  # tektonTasksNamespace: pipelines # Awailable from 4.14
  featureGates:
    deployTektonTaskResources: true
