apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hyperconverged-config
spec:
  destination:
    name: ""
    namespace: openshift-cnv
    server: "https://kubernetes.default.svc"
  source:
    path: gitops/virtualization
    repoURL: "https://github.com/jwerak/roadshow_ocpvirt_cicd.git"
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
